stages:
  - build

build:
  image: clibing/alpine-build:x86_64-1.0
  stage: build
  script:
    - bash cmvn -T 4 clean install deploy -Dmaven.test.skip=true
  tags:
#    - proxmox
    - vps    
#    - git.linuxcrypt.cn
  when: manual
